version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: college-schedule-postgres
    environment:
      POSTGRES_DB: college-schedule-db
      POSTGRES_USER: admin69
      POSTGRES_PASSWORD: admin69
    ports:
      - "5434:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./db:/docker-entrypoint-initdb.d
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U admin69 -d college-schedule-db" ]
      interval: 5s
      timeout: 5s
      retries: 5

  adminer:
    image: adminer
    container_name: college-schedule-adminer
    ports:
      - "8080:8080"
    depends_on:
      postgres:
        condition: service_healthy

volumes:
  pgdata:
    name: college-schedule-pgdata
